# version: '3.8'

services:
  rag-app:
    build: .
    container_name: tula_rag_system
    volumes:
      # Пробрасываем папки, чтобы данные сохранялись на вашем компьютере
      - .:/app
      - ./db_metadata:/app/db_metadata
      - ./chroma_db_store:/app/chroma_db_store
    environment:
      - PYTHONUNBUFFERED=1