name: sql_genius

services:
  # Наша локальная база метаданных
  db:
    image: postgres:15
    container_name: sql_metadata_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-app_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-app_password}
      POSTGRES_DB: ${POSTGRES_DB:-metadata_db}
    ports:
      - "5432:5432"
    volumes:
      - ./docker/db_init/init_fixed.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app_user -d metadata_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Векторная база для RAG
  chroma:
    image: chromadb/chroma:0.5.23
    container_name: chroma_db
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma/data

  # Наше FastAPI приложение
  app:
    build: 
      context: .
      dockerfile: Dockerfile
      network: host
    container_name: sql_genius_app
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "8080:8080"
    # Для разработки удобно монтировать код внутрь
    volumes:
      - ./src:/app/src
      - ./data:/app/data
    extra_hosts:
      - "tula-db2:10.209.109.230"
    dns:
      - 8.8.8.8
      - 8.8.4.4

volumes:
  postgres_data:
  chroma_data: